### ISSUE TITLE
2 particular signs don't seem to work on my playthru...

### ISSUE THREAD

**Issue by Snayjay** [jcdcdev/jcdcdev.Valheim.Signs#10]
### Which version are you using?

0.4.5

### Bug summary

I have the .dll installed in the plugins folder however I'm also running AzuAntiCheat for server sync and so you have to have the .dll in the config / whitelist folder.  So technically I have it there as well.  I've also tried loading the world with only 1 copy loaded and tried it in both locations.  No matter how it's loaded, the signs show "DYNAMIC" when in game...all the signs worked EXCEPT for {{deathBoard}} and {{deathCount}}.  I tried putting the signs up before I ever died.... I tested leaving the sign up and then dying.... and I tried redoing the sign after I had died.... nothing seems to make them work.  Appreciate anythoughts as the deathboard was really the only use I wanted.  Playing a hardcore server so I think it would be cool to see who's dying the most.

### Steps to reproduce

Placed the sign and typed "{{deathBoard}}"  and also tried "{{deathCount}}"

### Expected result / actual result

I expected those 2 signs to show me my deathcount and death leaderboard... but even though all the other signs worked.... these 2 did not.

**Comment by Snayjay** [comment]
Ok... tried again after writing this and {{deathCount}} is working.... but {{deathBoard}} is still not working.

**Comment by jcdcdev** [comment]
Hi @Snayjay please could you check the following:

- On the server - Is there a file called `death-leaderboard.json` file in `config/jcdcdev.Valheim.Signs`? 

- Please replicate the issue and send any server logs

- How is your server hosted? (single player, self hosted, paid hosting etc)

**Comment by Snayjay** [comment]
I made a video for you.... too much to explain.

https://drive.google.com/file/d/1HP4jMJUlsgPvAhw5C8BI0B5thPVQej4p/view?usp=drive_link

**Comment by jcdcdev** [comment]
So it looks as if the mod is successfully creating the leaderboard file. If you open it is there any data inside?

Please could you send me your server logs. Currently there is nothing to explain why it is not working ☹️

**Comment by Snayjay** [comment]
<img width="1280" alt="Signs file" src="https://github.com/user-attachments/assets/08fdb30f-ead9-4ad3-92ff-00f965c633c5">

This is what the .json file shows

**Comment by Snayjay** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17250945/LogOutput.log)

Here's my last output log.

**Comment by Snayjay** [comment]
Hey just FYI... everything is working now.  I was having issues with AzuAntiCheat and ServerCharacters... and after talking with Azumatt he explained a few things about installing everything and I'm in the process of reinstalling ALL my mods now and this one is working perfectly now.  Thanks for assisting me.

**Comment by jcdcdev** [comment]
Hi @Snayjay I'm glad things are working for you!
