### ISSUE TITLE
Feature request. Eitr refinery contents

### ISSUE THREAD

**Issue by Karmacopper** [jcdcdev/jcdcdev.Valheim.Signs#11]
### Feature summary

As a picture paints a thousand words, 
![892970_30](https://github.com/user-attachments/assets/5bd87998-22ab-4ab5-b359-2ceb148b892a)

As you can see, my Eitr refinery is entombed in marble and fed via hoppers and pipes. As such, I don't know its current inventory content. You mod would be ideal to furnish this need.

**Comment by jcdcdev** [comment]
Hi @Karmacopper, thanks for the suggestion! 😄 

I'll try to add this to the mod soon.

**Comment by jcdcdev** [comment]
Hi @Karmacopper, this has been added in `0.7.0` 😄
