### ISSUE TITLE
bug with signs

### ISSUE THREAD

**Issue by Thalanc** [jcdcdev/jcdcdev.Valheim.Signs#18]
### Feature summary

i started a new world with 2 new character mine and a friend and when we put up a death board it pulled other characters from other worlds games.. they have never been in this new world ?? how do you clear that so it shows only the new charcters?

**Comment by jcdcdev** [comment]
Hi @Thalanc 

To reset the deathboard please delete the following file:
`BepInEx\config\jcdcdev.Valheim.Signs\death-leaderboard.json`
