### ISSUE TITLE
DeathCount

### ISSUE THREAD

**Issue by pixeldiablo** [jcdcdev/jcdcdev.Valheim.Signs#20]
### Bug summary

Not really sure it’s a bug or how it’s intended to work.
Does the DeathCount work for current session’s deaths? i installed it with the purpose of keeping a visual track of my total deaths on a run, several sessions, so not sure if it’s not counting them or just works for deaths during a session and resets after logout.

### Steps to reproduce

Create sign, add code for death count, no count shown.

### Expected result / actual result

I can see my death count with the /stats command and it’ll show the total deaths for my character on that world “2”, with the mod sign i see “0”, same with the default code and using player’s name.

**Comment by jcdcdev** [comment]
Hi @pixeldiablo

**Does the DeathCount work for current session’s deaths?**

Yes - on player death the server increments the count in the following file `BepInEx\config\jcdcdev.Valheim.Signs\death-leaderboard.json`

- Does the leaderboard file exist on your server? (or on your local machine if self-hosting)
- If so, does your server logs contain any errors?

**Comment by pixeldiablo** [comment]
Thanks for replying, I just got a chance to check the files you mentioned.
It's a local world and it does have the JSON file on that location, which shows the deathcount "0", what I know for sure should be 2, and if I use the stats command, that's what it shows.
I don't really see any errors on the logfile but I might be looking at the wrong one, FYI, I'm using Thunderstore to install the mods.

![bepinex 121224](https://github.com/user-attachments/assets/2e211660-d945-4a5f-9a87-22e4d83b5e5e)

![deathcount0 121224](https://github.com/user-attachments/assets/41d86507-7ae1-4612-b0fb-4e32595c8bb4)


[death-leaderboard.json](https://github.com/user-attachments/files/18105925/death-leaderboard.json)

**Comment by pixeldiablo** [comment]
I notice now that this will count any death “after”, or maybe it’s just “while” using the mod and doesn’t take into account any other previous death or count that the game is taking record of. It’s a good thing to consider.

**Comment by jcdcdev** [comment]
Hi @pixeldiablo,

That's correct, the mod has its own way of tracking deaths (it isn't possible to get _other_ player's death info, particularly when they are not online).

As a result, only deaths that occur when the mod is installed will be tracked.

You can always adjust the leadboard file manually to align it with existing deaths 😀
