### ISSUE TITLE
Not displaying properly - Displays what I input, rather than what it should.

### ISSUE THREAD

**Issue by kebabthief** [jcdcdev/jcdcdev.Valheim.Signs#7]
### Which version are you using?

0.3.1

### Bug summary

The sign displays what I typed, rather than the time.

I've uploaded an image of the sign.

https://ibb.co/3Szqk7b

### Steps to reproduce

I don't know what is causing it.  It always displays like that.  Here is a link to the modpack that myself and my family use on our dedicated server.

https://thunderstore.io/c/valheim/p/EpicPotato/KebabWorldModPack/

### Expected result / actual result

Expected: To show the game time / Actual Displays {{GAMETIME}}

**Comment by jcdcdev** [comment]
Hi @kebabthief thank you for raising this issue. It's likely one of the mods in that pack is conflicting with this mod.

Do you have any server logs?

I'll set up a local server with your modpack and attempt to replicate the issue

**Comment by kebabthief** [comment]
> Hi @kebabthief thank you for raising this issue. It's likely one of the mods in that pack is conflicting with this mod.
> 
> Do you have any server logs?
> 
> I'll set up a local server with your modpack and attempt to replicate the issue

Thanks for the quick reply.  Which log is it that you need? In the ValheimServer/logs folder, there are 19 log files.  Only half of them were updated today.

**Comment by kebabthief** [comment]
I've just had a thought.  When I first installed it, it worked as intended, so if a mod has caused it not to work, it will probably be one that I installed after Signs.  Unless another mod that has since been updated is causing it.

Here are the mods that I installed after Signs.

https://ibb.co/Svv9HDS

**Comment by jcdcdev** [comment]
Hi @kebabthief, I was able to replicate the issue locally and have made a fix. (cool modpack by the way 😄)

Please can you update to 0.3.2 and let me know if it works?

**Comment by kebabthief** [comment]
> Hi @kebabthief, I was able to replicate the issue locally and have made a fix. (cool modpack by the way 😄)
> 
> Please can you update to 0.3.2 and let me know if it works?

Thank you very much :)

Only one problem.  I can no longer find the mod on Thunderstore.

**Comment by jcdcdev** [comment]
Hi @kebabthief, it keeps getting flagged for moderation on Thunderstore. It should be available now - https://thunderstore.io/package/download/jcdcdev/Signs/0.3.2/

**Comment by kebabthief** [comment]
> Hi @kebabthief, it keeps getting flagged for moderation on Thunderstore. It should be available now - https://thunderstore.io/package/download/jcdcdev/Signs/0.3.2/

Thank you.  The game time clock works perfectly now.

I've found another issue.  Do you want me to post it in here, or should I make a new thread?

**Comment by jcdcdev** [comment]
Hi @kebabthief, I'm glad the clock is now working. 

I'm sorry to hear there's another issue. Please do open a new issue as it is easier for me to track and progress.

I'll jump on it after work ☺

**Comment by kebabthief** [comment]
> Hi @kebabthief, I'm glad the clock is now working.
> 
> I'm sorry to hear there's another issue. Please do open a new issue as it is easier for me to track and progress.
> 
> I'll jump on it after work ☺

Thank you.  I should become your head beta tester 🤣

I've set up a new thread with something else that I've encountered (just to keep you busy)
