### ISSUE TITLE
Death Count with Split Names

### ISSUE THREAD

**Issue by kebabthief** [jcdcdev/jcdcdev.Valheim.Signs#8]
### Which version are you using?

0.4.1

### Bug summary

I'm stuggling to get the Death Count signs displaying the death count for a player with split names (i.e. two words as a name)

### Steps to reproduce

Create a death count sign for a player with a name with two or more words.

I've tried a few different ways.  I've tried just as normal, {{deathCount Dave Jones}}
I've tried with quotation marks, {{deathCount "Dave Jones"}}
I've tried with an underscore, {{deathCount Dave_Jones}}
I've tried all lower case, {{deathCount dave_jones}}, {{deathCount dave jones}} and {{deathCount "dave jones"}}

All attempts display on the sign ERROR (in red) then PLAYER NOT FOUND (in the default colour).

### Expected result / actual result

Expected: To display the death count.  Actual: ERROR PLAYER NOT FOUND

**Comment by jcdcdev** [comment]
Hi @kebabthief, thank you for reporting this issue.

The code responsible for getting the player name/id from the sign does not expect spaces in names.

For anyone interested here is the code in question: https://github.com/jcdcdev/jcdcdev.Valheim.Signs/blob/316ad3089b4626c84493d80d8a06c22094182ccf/src/jcdcdev.Valheim.Signs/Converters/DeathCountSign.cs#L17 

Once fixed you will able to enter the player's name as expected, e.g `Dave Jones`

**Comment by kebabthief** [comment]
> Hi @kebabthief, thank you for reporting this issue.
> 
> The code responsible for getting the player name/id from the sign does not expect spaces in names.
> 
> For anyone interested here is the code in question:
> 
> https://github.com/jcdcdev/jcdcdev.Valheim.Signs/blob/316ad3089b4626c84493d80d8a06c22094182ccf/src/jcdcdev.Valheim.Signs/Converters/DeathCountSign.cs#L17
> 
> Once fixed you will able to enter the player's name as expected, e.g `Dave Jones`

Thank you for the swift reply.  Can you explain it to me as if I'm a Labrador?

I can't find a file called DeathCountSigns.cs in my mod or config folder.  I can go to the link in your GitHub.

Do I need to change something in the .dll?

PS.  I just used "Dave Jones" as an example.  My player name is Potatis Gris, and my daughter's player name is Croosty Toost.

**Comment by jcdcdev** [comment]
Apologies for any confusion - this is something I need to fix in the source code and release a new version of the mod ☺

I should get it done later today

**Comment by kebabthief** [comment]
> Hi @kebabthief version 0.4.2 fixes this issue.
> 
> Please let me know if that resolves things for you too 😄

Hi jcd,

It now recognises players with split names.  Thank you.

Can I just ask where it's getting the numbers from?  Is it the number of deaths since the mod was installed?

**Comment by kebabthief** [comment]
Ah.  Don't worry, mate.

I've found the .json folder 😉
